# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15df0255ed8ca9f6195099cd59e5fddaab29bae216a228290ed9ca2d5f01dbde7794113b9cf14e2910f23e6a1cb0a5500d71d7c2624497c5a5822e46ba43bcd3

test:
  secret_key_base: 9b036a3981ad1345bd2d7ef671ae24bb9707906335f5e264c0e74bb12d5d160f064bb9a5d49ec339b25194a1cbf3d8b2b439a3967553c32e07f29ebc411d6277

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
